import { Menu } from "@/types/menu";

const menuData: Menu[] = [
  {
    id: 1,
    title: "Home",
    newTab: false,
    path: "/",
  },
 {
  id: 2,
  title: "Services",
  path: "/services",  
  newTab: false,
  submenu: [
    { id: 21, title: "Assignment", path: "/services/assignments", newTab: false },
    { id: 22, title: "Do My Assignment", path: "/services/do-my-assignment", newTab: false },
    { id: 23, title: "Do My Homework", path: "/services/do-my-homework", newTab: false },
    { id: 24, title: "Do My Maths Homework", path: "/services/do-my-maths-homework", newTab: false },
    { id: 25, title: "Lab Report", path: "/services/lab-report", newTab: false },
    { id: 26, title: "Live Session", path: "/services/live-session", newTab: false },
    { id: 27, title: "Online Tutoring", path: "/services/online-tutoring", newTab: false },
    { id: 28, title: "Project Report Writing", path: "/services/project-report-writing", newTab: false },
    { id: 29, title: "Paper Writing Help", path: "/services/paper-writing-help", newTab: false },
    { id: 30, title: "Project Report Help", path: "/services/project-report-help", newTab: false },
    { id: 31, title: "Presentation Writing", path: "/services/presentation-writing", newTab: false },
    { id: 32, title: "Pay Someone To Do My Homework", path: "/services/pay-someone-to-do-my-homework", newTab: false },
    { id: 33, title: "Paying Someone To Write Your Paper", path: "/services/paying-someone-to-write-your-paper", newTab: false },
    { id: 34, title: "Speech Writing", path: "/services/speech-writing", newTab: false },
    { id: 35, title: "Video Solutions", path: "/services/video-solutions", newTab: false },
    { id: 36, title: "Write Research Paper", path: "/services/write-research-paper", newTab: false },
  ],
},

  {
    id: 3,
    title: "Subjects",
    newTab: false,
    submenu: [
      {
        id: 31,
        title: "Programming",
        newTab: false,
        submenu: [
          { id: 311, title: "C#", path: "/subjects/c-homework-help", newTab: false },
          { id: 312, title: "Coding", path: "/subjects/coding-homework-help", newTab: false },
          { id: 313, title: "Assembly Programming", path: "/subjects/assembly-programming-homework-help", newTab: false },
          { id: 314, title: "Cryptography", path: "/subjects/cryptography-homework-help", newTab: false },
          { id: 315, title: "Machine Learning", path: "/subjects/machine-learning-homework-help", newTab: false },
          { id: 316, title: "Natural Language Processing", path: "/subjects/natural-language-processing-homework-help", newTab: false },
          { id: 317, title: "Prolog Programming", path: "/subjects/prolog-programming-homework-help", newTab: false },
          { id: 318, title: "Artificial Intelligence", path: "/subjects/artificial-intelligence-homework-help", newTab: false },
          { id: 319, title: "Formal Language Automata", path: "/subjects/formal-language-automata-homework-help", newTab: false },
          { id: 320, title: "Design And Analysis Of Algorithms", path: "/subjects/design-and-analysis-of-algorithms-homework-help", newTab: false },
          { id: 321, title: "Data Science", path: "/subjects/data-science-homework-help", newTab: false },
          { id: 322, title: "Big Data", path: "/subjects/big-data-homework-help", newTab: false },
          { id: 323, title: "Object Oriented Analysis And Design", path: "/subjects/object-oriented-analysis-and-design-homework-help", newTab: false },
          { id: 324, title: "Computer Organisation And Architecture", path: "/subjects/computer-organisation-and-architecture-homework-help", newTab: false },
          { id: 325, title: "Operating System", path: "/subjects/operating-system-homework-help", newTab: false },
          { id: 326, title: "Compiler Design", path: "/subjects/compiler-design-homework-help", newTab: false },
          { id: 327, title: "Programming Language Principle And Paradigm", path: "/subjects/programming-language-principle-and-paradigm-homework-help", newTab: false },
          { id: 329, title: "Computer Networks", path: "/subjects/computer-networks-homework-help", newTab: false },
          { id: 330, title: "Internet Of Things", path: "/subjects/internet-of-things-homework-help", newTab: false },
          { id: 331, title: "Deep Learning", path: "/subjects/deep-learning-homework-help", newTab: false },
          { id: 332, title: "Discrete Mathematics", path: "/subjects/discrete-mathematics-homework-help", newTab: false },
          { id: 333, title: "Haskell Programming", path: "/subjects/haskell-programming-homework-help", newTab: false },
          { id: 334, title: "Data Structures And Algo", path: "/subjects/data-structures-and-algo-homework-help", newTab: false },
          { id: 335, title: "Cyber Security", path: "/subjects/cyber-security-homework-help", newTab: false },
          { id: 336, title: "Android App Development", path: "/subjects/android-app-development-homework-help", newTab: false },
          { id: 337, title: "Java", path: "/subjects/java-homework-help", newTab: false },
          { id: 338, title: "Python", path: "/subjects/python-homework-help", newTab: false },
          { id: 339, title: "R Programming", path: "/subjects/r-programming-homework-help", newTab: false },
          { id: 340, title: "Software Engineering", path: "/subjects/software-works-homework-help", newTab: false },
          { id: 341, title: "Multimedia Technology", path: "/subjects/multimedia-technology-homework-help", newTab: false },
          { id: 342, title: "Agile Software Development", path: "/subjects/agile-software-development-homework-help", newTab: false },
          { id: 343, title: "DBMS", path: "/subjects/dbms-homework-help", newTab: false },
          { id: 344, title: "Real Time System", path: "/subjects/real-time-system-homework-help", newTab: false },
          { id: 345, title: "Distributed Computing", path: "/subjects/distributed-computing-homework-help", newTab: false },
          { id: 346, title: "Cloud Computing", path: "/subjects/cloud-computing-homework-help", newTab: false },
          { id: 347, title: "Data Mining", path: "/subjects/data-mining-homework-help", newTab: false },
          { id: 348, title: "Mobile Computing", path: "/subjects/mobile-computing-homework-help", newTab: false },
          { id: 349, title: "Data Warehousing", path: "/subjects/data-warehousing-homework-help", newTab: false },
          { id: 350, title: "C/C++", path: "/subjects/cc-homework-help", newTab: false },
          { id: 351, title: "Excel", path: "/subjects/excel-homework-help", newTab: false },
          { id: 352, title: "Web Designing and Development", path: "/subjects/web-designing-and-development-homework-help", newTab: false },
          { id: 353, title: "React", path: "/subjects/react-homework-help", newTab: false },
        ],
      },
      {
        id: 42,
        title: "Computer Science",
        newTab: false,
        submenu: [
          { id: 421, title: "Machine Learning", path: "/subjects/computer-science/machine-learning", newTab: false },
          { id: 422, title: "Artificial Intelligence", path: "/subjects/computer-science/artificial-intelligence", newTab: false },
          { id: 423, title: "Data Science", path: "/subjects/computer-science/data-science", newTab: false },
          { id: 424, title: "Cryptography", path: "/subjects/computer-science/cryptography", newTab: false },
          { id: 425, title: "Big Data", path: "/subjects/computer-science/big-data", newTab: false },
        ],
      },
      {
        id: 53,
        title: "Mathematics",
        newTab: false,
        submenu: [
          { id: 531, title: "Statistics", path: "/subjects/mathematics/statistics", newTab: false },
          { id: 532, title: "Calculus", path: "/subjects/mathematics/calculus", newTab: false },
          { id: 533, title: "Algebra", path: "/subjects/mathematics/algebra", newTab: false },
        ],
      },
      {
        id: 64,
        title: "Management",
        newTab: false,
        submenu: [
          { id: 641, title: "Marketing", path: "/subjects/management/marketing", newTab: false },
          { id: 642, title: "Finance", path: "/subjects/management/finance", newTab: false },
          { id: 643, title: "Human Resource", path: "/subjects/management/hr", newTab: false },
        ],
      },
      {
        id: 75,
        title: "Engineering",
        newTab: false,
        submenu: [
          { id: 751, title: "Mechanical", path: "/subjects/engineering/mechanical", newTab: false },
          { id: 752, title: "Civil", path: "/subjects/engineering/civil", newTab: false },
          { id: 753, title: "Electrical", path: "/subjects/engineering/electrical", newTab: false },
          { id: 754, title: "Chemical", path: "/subjects/engineering/chemical", newTab: false },
        ],
      },
      {
        id: 86,
        title: "Arts & Humanities",
        newTab: false,
        submenu: [
          { id: 861, title: "History", path: "/subjects/arts/history", newTab: false },
          { id: 862, title: "Sociology", path: "/subjects/arts/sociology", newTab: false },
          { id: 863, title: "English Literature", path: "/subjects/arts/english", newTab: false },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Blogs",
    newTab: false,
    path: "/blog",
  },
  {
    id: 5,
    title: "Reviews",
    newTab: false,
    path: "/reviews",
  }
];

export default menuData;

